### ISSUE TITLE
0.0.4. Not working

### ISSUE THREAD

**Issue by wifi75** [LeskoIam/kronoterm_cloud_relay#11]
Hello yes, mi .env it is ok with my credential, but not working.
![image](https://github.com/user-attachments/assets/22448deb-2953-4dfd-bf55-6a604a0e4ffd)
![image](https://github.com/user-attachments/assets/e4a8784b-22b8-4faa-b3a2-db990524f284)

**Comment by wifi75** [comment]
![image](https://github.com/user-attachments/assets/c9af97be-cdd3-469c-adb5-f0ce165c5e0c)

**Comment by LeskoIam** [comment]
I think 'Nome utente o password errato'? means 'Incorrect username or password' so there has to some typo...

**Comment by LeskoIam** [comment]
> And please use `nano .env` on console to confirm there are no extra characters (`\n`or `\r`) at the end of the line.

Well then, I have no idea any more. The error message is returned from the cloud and is pretty clear on what's wrong.

**Comment by wifi75** [comment]
my credentials are in uppercase, could that be the problem?

**Comment by LeskoIam** [comment]
Shouldn't be a problem. You can try using `"`
```env
KRONOTERM_CLOUD_USER="UsEr nA Me"
KRONOTERM_CLOUD_PASSWORD="PaSs Word"
```

**Comment by wifi75** [comment]
Yesss !!!


![image](https://github.com/user-attachments/assets/62a71f0f-a556-4399-ac67-bcbff16f57dd)
![image](https://github.com/user-attachments/assets/10c32676-b56a-43f1-98d4-c41f44e92625)

**Comment by wifi75** [comment]
![image](https://github.com/user-attachments/assets/63e3d3c2-49a2-456f-ab08-ab4c97d8d4a8)

**Comment by LeskoIam** [comment]
YES!!!!!! I'm so glad it works!!!! I hope you'll b able to get it integrated into home assistant. I hope the [instructions ](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/master/docs/home_assistant.md) are OK. Open an issue if you hit any problems.
