### ISSUE TITLE
Missing domestic hot water boiler

### ISSUE THREAD

**Issue by wifi75** [LeskoIam/kronoterm_cloud_relay#16]
Hi, I realized that all the values ​​for 'domestic hot water' are missing, can they be added?

![image](https://github.com/user-attachments/assets/a1f98774-f217-4090-8238-db8fc000f66b)

**Comment by LeskoIam** [comment]
Yes, the plan is to add all relevant data and also relevant input configurations (OFF, ON, set temp,...). If you are not getting the correct data into home assistant it's probably due to #15 #17 .

**Comment by LeskoIam** [comment]
Hey! Added in [v0.0.14](https://github.com/LeskoIam/kronoterm_cloud_relay/releases/tag/0.0.14).
