### ISSUE TITLE
Modbus Kronoterm internal document

### ISSUE THREAD

**Issue by iLLiac4** [LeskoIam/kronoterm_cloud_relay#19]
Hi. Maybe you will find this document useful with all the addresses. Maybee this way it is possible to control it localy with modbus and I assume the info is then also pushed to the cloud if you change it over modbus. Haver fun ;)
[Modbus CNS TT3000web1_0 (1).pdf](https://github.com/user-attachments/files/17108656/Modbus.CNS.TT3000web1_0.1.pdf)

**Comment by LeskoIam** [comment]
@iLLiac4 Thank you very much! This is the info I'm looking for, wonderful!
