### ISSUE TITLE
Web modul TT3000 sd card backup.

### ISSUE THREAD

**Issue by iLLiac4** [LeskoIam/kronoterm_cloud_relay#20]
If you sd card died here is the content to rebuild the sd card. FAT32 and copy the content of the compressed folder to micro sd card.
[WEB_SD.zip](https://github.com/user-attachments/files/17118395/WEB_SD.zip)

**Comment by LeskoIam** [comment]
Oh, I know what that is. Thank you again, really appreciate it!
