### ISSUE TITLE
Help missing

### ISSUE THREAD

**Issue by wifi75** [LeskoIam/kronoterm_cloud_relay#4]
Hello can you make help for install on debian server o ubuntu?

**Comment by LeskoIam** [comment]
Added more installation details in #6 

Preview [here](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md)

**Comment by wifi75** [comment]
> Added more installation details in #6
> 
> Preview [here](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md).

see below
![image](https://github.com/user-attachments/assets/9c3a5980-1340-4d64-bb0b-fbd5c29fd92c)

**Comment by LeskoIam** [comment]
> > Added more installation details in #6
> > Preview [here](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md).
> 
> see below ![image](https://private-user-images.githubusercontent.com/31816231/366120807-9c3a5980-1340-4d64-bb0b-fbd5c29fd92c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODU0MjksIm5iZiI6MTcyNTk4NTEyOSwicGF0aCI6Ii8zMTgxNjIzMS8zNjYxMjA4MDctOWMzYTU5ODAtMTM0MC00ZDY0LWJiMGItZmJkNWMyOWZkOTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE2MTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTc5YTlhOTZlZTc5ODA3ODBiMmE0NGI0YTI0ZDY4ZTZiMWNlOTgyMTg2NmQzZWYxYjhjZmIwNzNlNWYzNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xlua8TMTY2pobC5LXOX7WP13rNX6U1WIqF-VF3E-cMo)

Try running wirh `python3 -m` e.g.:
`nohup python3 -m flask --app kronoterm_cloud_relay run --host=0.0.0.0 --port=8555 &`

**Comment by wifi75** [comment]
![image](https://github.com/user-attachments/assets/f792073c-de3a-41a8-9180-5804e8b859d6)

**Comment by wifi75** [comment]
> * http://ip-or-host-address/hp-info/info_summary
not working

![image](https://github.com/user-attachments/assets/2b3a239c-436c-4872-8b74-76438dc9955d)

**Comment by wifi75** [comment]
also with the port 8555

![image](https://github.com/user-attachments/assets/67af3352-eabc-4ecc-8b57-876f2daf1108)

**Comment by LeskoIam** [comment]
> also with the port 8555
> 
> ![image](https://private-user-images.githubusercontent.com/31816231/366133904-67af3352-eabc-4ecc-8b57-876f2daf1108.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODcxOTIsIm5iZiI6MTcyNTk4Njg5MiwicGF0aCI6Ii8zMTgxNjIzMS8zNjYxMzM5MDQtNjdhZjMzNTItZWFiYy00ZWNjLThiNTctODc2ZjJkYWYxMTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE2NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYWY5ZDlhNWZmNWM0Njg5ZWUyMDAyOTFjOWIwMGY4ZjQ5MzcyNzlmMmY1NmFlMjJjMmQ2Njg3M2YzN2Y4MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tkoMyOiK3V6I9DChYQBfjURb_Gf-JZt6_F4OzBP2_hQ)

Please post content of `nohup.out` there should be an error there.

For reference here is my URL `http://192.168.0.230:8555/hp-info/info_summary` so yours looks OK.

**Comment by wifi75** [comment]
see my file nohup

[nohup.zip](https://github.com/user-attachments/files/16948260/nohup.zip)

**Comment by LeskoIam** [comment]
From the `nohup.out` I can see two things:
- Port 8555 is in use by another program. Either identify and stop that program, or start the server with a different port.
  - You are trying to run two services on the same port, do you have two instances of relay running? `ps aux | grep python`
  - Do you have any other web services running on the same machine? If so try changing the port in run command (`nohup python -m ...`) to something like 8557
- Kronoterm API could be different. Which heat pump do you have? I'll add more logging (#7 ) in the future so I can see exactly what API is sending.

**Comment by wifi75** [comment]
I restarted the server...
now the service starts automatically?

**Comment by wifi75** [comment]
too complicated....
the system doesn't work for me, maybe I should give up

**Comment by wifi75** [comment]
![image](https://github.com/user-attachments/assets/a373254e-afbe-4b08-8843-7e7a186cef06)
![image](https://github.com/user-attachments/assets/eefa7542-b151-46d4-ae48-adaf49277e14)

**Comment by LeskoIam** [comment]
You also don't follow and read instructions too good...

- Yes, you have to use `python3` instead of `python`,
- To install follow [README.txt](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md), steps `1.` to `7.`,
- You install only once,
- To run (after reboot for example) follow [README.txt](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md), steps `5.` (skip `python -m venv .venv` step) to `7.`,
- It is possible something is already running on the same port (8555) on your machine (change the port),
- This software is in development (pre-alpha) phase and is distributed as such. It is not mature enough and does require some knowledge from the user,
- I only have one device to test on and can't know what setup you are running,
- There is [debugging](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md#debugging) section in the [README.txt](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md).

Perhaps in one of the future releases things will be easier to install/run but for now it is what it is.

I would be vary happy to get some feedback from you. What heat pump do you have, which model? Could you get me API response data in the future when `kronoterm_cloud_relay` logging will be improved?

**Comment by wifi75** [comment]
of course I can help you .... my kronoterm is Adapt 0312

**Comment by wifi75** [comment]
> You also don't follow and read instructions too good...
> 
> * Yes, you have to use `python3` instead of `python`,
> * To install follow [README.txt](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md), steps `1.` to `7.`,
> * You install only once,
> * To run (after reboot for example) follow [README.txt](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md), steps `5.` (skip `python -m venv .venv` step) to `7.`,
> * It is possible something is already running on the same port (8555) on your machine (change the port),
> * This software is in development (pre-alpha) phase and is distributed as such. It is not mature enough and does require some knowledge from the user,
> * I only have one device to test on and can't know what setup you are running,
> * There is [debugging](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md#debugging) section in the [README.txt](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/d4667314fb2936cb787dccda576ccc13485b825e/README.md).
> 
> Perhaps in one of the future releases things will be easier to install/run but for now it is what it is.
> 
> I would be vary happy to get some feedback from you. What heat pump do you have, which model? Could you get me API response data in the future when `kronoterm_cloud_relay` logging will be improved?

![image](https://github.com/user-attachments/assets/5c79481e-40c2-4f9d-baa7-0aa835dbe680)

![image](https://github.com/user-attachments/assets/3fb7d118-d1ac-4f83-92bc-18cfa477a106)

![image](https://github.com/user-attachments/assets/b2e45657-e9aa-450f-8773-d67e247f1444)

**Comment by LeskoIam** [comment]
For your first screenshot it's my mistake (again). It should be `... 5555/relay/echo` and it should return `echo` as 'message'.

For the second one I think API is different. But I do have the same heat pump as you so I'm not 100% sure what is going on. I'll make some updates to the app to log more data and you can try it and share the logs (I'll give you instructions if you are willing to help).

**Comment by wifi75** [comment]
ok.

**Comment by LeskoIam** [comment]
OK, I added more logging.

To get the new version do the following:

1. Delete the old version (0.0.2). E.g. manually from the file system,
2. re-install following the instructions in `README.md` and run in the foreground (refer to `README.md`),
   ```python
   python -m flask --app kronoterm_cloud_relay run --host=0.0.0.0 --port=8555
   ```

When you hit errors please send what is on the screen and also `nohup.out` file.

**Comment by wifi75** [comment]
ok installed new version 0.0.3
![image](https://github.com/user-attachments/assets/b90c486d-840e-48e1-8cd6-47eaa9dd43fd)

![image](https://github.com/user-attachments/assets/0c27c981-1802-4cf6-9155-30d8c408dd70)

**Comment by wifi75** [comment]
below

[nohup.zip](https://github.com/user-attachments/files/16965822/nohup.zip)

**Comment by LeskoIam** [comment]
You shared `nohup.out` from an old run with old version.

What I would like to have is the output on the console after these steps:

1. Run `python3 -m flask --app kronoterm_cloud_relay run --host=0.0.0.0 --port=8555`,
2. go to `http://ip-or-host-address:8555/hp-info/info_summary`,
3. there should be some output on the console (where you ran `python3 -m flask ...`).

**OR** `nohup.out` file after these steps:

1. Run `nohup python3 -m flask --app kronoterm_cloud_relay run --host=0.0.0.0 --port=8555 &`,
2. go to `http://ip-or-host-address:8555/hp-info/info_summary`,
3. run `cat nohup.out` (in the `src` directory) and make sure lines with current timestamp are there,
4. share `nohup.out` as before.

**Comment by wifi75** [comment]
![image](https://github.com/user-attachments/assets/f102e1f1-c5c3-44de-8a04-3ef495e3b90d)

![image](https://github.com/user-attachments/assets/454b1c88-2d75-4376-aadf-52a6dfaa3b84)

[nohup.zip](https://github.com/user-attachments/files/16974614/nohup.zip)

**Comment by LeskoIam** [comment]
Thanks!

This line indicates that kronoterm cloud page is trying to show a popup window or similar... hmmm...
`2024-09-11 14:02:34,547 [    INFO] [kronoterm_cloud_api.py:  71:             get_raw()]	GET RESP: '{"result": "action", "js": "window.location=\"https://cloud.kronoterm.com\""}'`

What is your kronoterm cloud address (mine is `https://cloud.kronoterm.com/`)? Can you screenshot your kronoterm cloud page (I just want to see if it's different interface)?

**Comment by wifi75** [comment]
![image](https://github.com/user-attachments/assets/7d7310bf-8aca-4870-b223-563260e71d12)

**Comment by LeskoIam** [comment]
OK, it looks the same.

I think we are getting close, it's just hard debugging through comments here hehe.

Something is different on your end, specifically with how kronoterm API works or not works... I would have to manually try and login into your cloud account to see what API calls and responses are being sent and received ... 

So for now I must say I can solve this issue.
