### ISSUE TITLE
error during install kronoterm cloud relay

### ISSUE THREAD

**Issue by wifi75** [LeskoIam/kronoterm_cloud_relay#5]
hello, I will try to instyall kronoterm relay to new server debian 12 on my proxmox
see below 
![image](https://github.com/user-attachments/assets/7eb9c11b-866b-4d1c-b7df-7b1af5ea7d38)

**Comment by LeskoIam** [comment]
I believe adding better documentation (#4) will solve this issue also.

**Comment by wifi75** [comment]
yes if you can do a step by step installation, for me who am not very practical, I could manage to have a working server and with the service that starts automatically when the server is restarted
Thanks

**Comment by wifi75** [comment]
hello any news?

**Comment by LeskoIam** [comment]
I'm getting version 0.0.4 ready, probably ready to try this week.

**Comment by LeskoIam** [comment]
Hey @wifi75! Version [0.0.4](https://github.com/LeskoIam/kronoterm_cloud_relay/releases/tag/0.0.4) is ready. If you want you can test it out.
Please make sure:
- to delete the old install and start fresh,
- study the [README.md](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/dev/README.md) on dev branch and [home_assistant.md](https://github.com/LeskoIam/kronoterm_cloud_relay/blob/dev/docs/home_assistant.md),
- please open new issue when/if something is not working and provide as much info as possible.

Best regards!

**Comment by wifi75** [comment]
hello new version installed

![image](https://github.com/user-attachments/assets/4b94d8f7-761e-4016-a77c-c29ce4e8552d)

[nohup.zip](https://github.com/user-attachments/files/17043704/nohup.zip)

**Comment by wifi75** [comment]
![image](https://github.com/user-attachments/assets/a1d21e39-f021-44df-a224-17563d968f08)

**Comment by LeskoIam** [comment]
I guess you didn't set your username and password in `.env`.

Please, read the readme file, the url you show in the screenshot is not even valid for the API.... But first make sure you have `.env` configured.

Also, this issue is now **closed**. When you get at least a step further open a [new issue](https://github.com/LeskoIam/kronoterm_cloud_relay/issues/new).
